version: '3.4'

services:
  entry_node:
    build: ./EntryNode
    ports:
      - "3000:3000"
    networks:
      - chord-network
  server_node:
    build: ./ServerNode
    image: server_node
    deploy:
      mode: replicated
      # number of server nodes
      replicas: 4
    networks:
      - chord-network

networks:
  chord-network:
